### PR TITLE
cmake: use package configuration file instead of find module

### PR DESCRIPTION
**Pull request by drizt**
Minimum required cmake version is increased.

### CODE REVIEW

**Comment by drizt** [comment]
Current FindTufao.cmake.in is not suitable for Linux distros. Linuxes often allow to have both versions (for i386 and x86_64) of devel packagaes installed in parallele. So common files must be the same. My patch solves this problem. Also I saved variables from current find module. So new version must be fully compatible with old.

**Comment by vinipsmaker** [comment]
After issuing `make install`, Tufão isn't ready for use.

Solve this issue, then I can accept the patch

**Comment by drizt** [comment]
What issue?  `make install` works for me on Mac OS, Fedora, Ubuntu, OpenSUSE and Debian.

**Comment by vinipsmaker** [comment]
`make install` does work, but looks like there are missing files for the installation. The cmake example (hello-cmake) doesn't compile anymore.

**Comment by drizt** [comment]
Ah, I missed major version in module name

**Comment by drizt** [comment]
fixed. try now.

**Comment by vinipsmaker** [comment]
[Merged](https://github.com/vinipsmaker/tufao/commit/d7d632415181f3140844e609c3b99aa1093cd04c).

**Pull request closed without merging**
